---
# file: tasks/main.yml
# Top-level installer for Nginx.
#
# @see http://wiki.nginx.org/Install

- name: install the latest version of nginx
  yum:
    name: nginx
    state: latest
  become: true

#- name: Copy nginx default.conf configuration for nginx to redirect to wordpress
#  copy:
#    src: default.conf
#    dest: /etc/nginx/conf.d/default.conf
#    state: absent
#  become: true

#- name: Copy nginx.conf configuration for nginx
#  copy:
#    src: nginx.conf 
#    dest: /etc/nginx/nginx.conf
#    state: absent
#  become: true

#force all handlers to run - so all db updates will take effect  
- meta: flush_handlers

